apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-simulation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trip-simulation
  template:
    metadata:
      labels:
        app: trip-simulation
    spec:
      containers:
      - name: trip-simulation
        image: shu1bham9/trip-simulation:latest
        ports:
        - containerPort: 8080
