apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deployer
  namespace: my-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-job-runner
  namespace: my-namespace
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-job-runner-binding
  namespace: my-namespace
subjects:
  - kind: ServiceAccount
    name: github-deployer
    namespace: my-namespace
roleRef:
  kind: Role
  name: github-job-runner
  apiGroup: rbac.authorization.k8s.io
