apiVersion: v1
kind: Service
metadata:
  name: trip-simulation-service
spec:
  type: LoadBalancer
  selector:
    app: trip-simulation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
